# Generated by Django 5.2.13 on 2026-05-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Онлайн'), ('onsite', 'На месте'), ('none', 'Не выбрано')], default='none', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость услуги (руб.)'),
        ),
    ]
