# Generated by Django 5.2.13 on 2026-05-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_payment_amount_alter_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('none', 'Не указан'), ('online', 'Онлайн (СБП)'), ('onsite', 'На месте')], default='none', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
